#!/usr/bin/env python3
""" Pygtk3 Clock
"""

import signal
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

import clockwidget


class Pygtk3ClockApplication(Gtk.Window):
    """ Draw an analogue clock in gtk3 with python
    """

    def __init__(self):
        Gtk.Window.__init__(self, title="Example Clock Widget")
        self.connect("delete-event", Gtk.main_quit)
        self.set_default_size(800, 800)

        self.clockwidget = clockwidget.ClockWidget()

        self.box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.add(self.box)

        self.box.add(self.clockwidget)

    def main(self):
        """ Run Gtk App
        """
        self.show_all()
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()


if __name__ == '__main__':
    Pygtk3ClockApplication().main()
