
// This file has been generated by the GUI designer. Do not modify.
namespace gtksharpclock
{
	public partial class Clock
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtksharpclock.Clock
			global::Stetic.BinContainer.Attach (this);
			this.Name = "gtksharpclock.Clock";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
